"""Comprehensive seed script for ministerial positions (2074-2082 BS).

Seeds all cabinet positions from major Nepal governments:
- Second Dahal Cabinet (Aug 2016 - May 2017)
- Fourth Deuba Cabinet (Jun 2017 - Feb 2018)
- Second Oli Cabinet (Feb 2018 - Jul 2021)
- Fifth Deuba Cabinet (Jul 2021 - Dec 2022)
- Third Dahal Cabinet (Dec 2022 - Jul 2024)
- Fourth Oli Cabinet (Jul 2024 - Sept 2025)

Run with: python -m scripts.seed_ministerial_positions_full

Data sourced from OPMCM records, Wikipedia, Kathmandu Post, and other news archives.
"""
import asyncio
import logging
from datetime import date
from uuid import uuid4

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.database import AsyncSessionLocal
from app.models.ministerial_position import MinisterialPosition

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


# =============================================================================
# COMPREHENSIVE MINISTERIAL DATA (2074-2082 BS / 2017-2025 AD)
# =============================================================================

MINISTERIAL_DATA = [
    # =========================================================================
    # SECOND DAHAL CABINET (Aug 3, 2016 - May 24, 2017) - 2073-2074 BS
    # =========================================================================

    # Prime Minister
    {
        "person_name_en": "Pushpa Kamal Dahal",
        "person_name_ne": "पुष्पकमल दाहाल",
        "position_type": "prime_minister",
        "ministry": None,
        "start_date": date(2016, 8, 3),
        "end_date": date(2017, 5, 24),
        "government_name": "Second Dahal Cabinet",
        "prime_minister": None,
        "party_at_appointment": "CPN (Maoist Centre)",
        "notes": "Second term as Prime Minister under new constitution.",
        "source": "opmcm",
    },

    # Deputy Prime Ministers
    {
        "person_name_en": "Bijaya Kumar Gachhadar",
        "person_name_ne": "विजयकुमार गच्छदार",
        "position_type": "deputy_pm",
        "ministry": "Local Development",
        "start_date": date(2016, 8, 5),
        "end_date": date(2017, 5, 24),
        "government_name": "Second Dahal Cabinet",
        "prime_minister": "Pushpa Kamal Dahal",
        "party_at_appointment": "Madhesi Janadhikar Forum Nepal (Democratic)",
        "notes": "Senior Deputy PM, headed Ministry of Local Development.",
        "source": "news_archive",
    },
    {
        "person_name_en": "Bimalendra Nidhi",
        "person_name_ne": "विमलेन्द्र निधि",
        "position_type": "deputy_pm",
        "ministry": "Home Affairs",
        "start_date": date(2016, 8, 5),
        "end_date": date(2017, 5, 24),
        "government_name": "Second Dahal Cabinet",
        "prime_minister": "Pushpa Kamal Dahal",
        "party_at_appointment": "Nepali Congress",
        "notes": "Deputy PM and Home Minister.",
        "source": "news_archive",
    },
    {
        "person_name_en": "Krishna Bahadur Mahara",
        "person_name_ne": "कृष्णबहादुर महरा",
        "position_type": "deputy_pm",
        "ministry": "Finance",
        "start_date": date(2016, 8, 5),
        "end_date": date(2017, 5, 24),
        "government_name": "Second Dahal Cabinet",
        "prime_minister": "Pushpa Kamal Dahal",
        "party_at_appointment": "CPN (Maoist Centre)",
        "notes": "Deputy PM and Finance Minister.",
        "source": "news_archive",
    },

    # Cabinet Ministers - Nepali Congress quota
    {
        "person_name_en": "Gagan Kumar Thapa",
        "person_name_ne": "गगन कुमार थापा",
        "position_type": "minister",
        "ministry": "Health and Population",
        "start_date": date(2016, 8, 25),
        "end_date": date(2017, 5, 24),
        "government_name": "Second Dahal Cabinet",
        "prime_minister": "Pushpa Kamal Dahal",
        "party_at_appointment": "Nepali Congress",
        "notes": "Implemented significant health sector reforms. Popular youth leader.",
        "source": "news_archive",
    },
    {
        "person_name_en": "Agni Prasad Sapkota",
        "person_name_ne": "अग्नि प्रसाद सापकोटा",
        "position_type": "minister",
        "ministry": "Land Reform and Management",
        "start_date": date(2016, 8, 25),
        "end_date": date(2017, 5, 24),
        "government_name": "Second Dahal Cabinet",
        "prime_minister": "Pushpa Kamal Dahal",
        "party_at_appointment": "CPN (Maoist Centre)",
        "notes": "Later became Speaker of House of Representatives.",
        "source": "news_archive",
    },

    # =========================================================================
    # FOURTH DEUBA CABINET (Jun 7, 2017 - Feb 15, 2018) - 2074 BS
    # =========================================================================

    # Prime Minister
    {
        "person_name_en": "Sher Bahadur Deuba",
        "person_name_ne": "शेरबहादुर देउवा",
        "position_type": "prime_minister",
        "ministry": None,
        "start_date": date(2017, 6, 7),
        "end_date": date(2018, 2, 15),
        "government_name": "Fourth Deuba Cabinet",
        "prime_minister": None,
        "party_at_appointment": "Nepali Congress",
        "notes": "Fourth term as Prime Minister. Oversaw local elections.",
        "source": "opmcm",
    },

    # Deputy Prime Ministers
    {
        "person_name_en": "Gopal Man Shrestha",
        "person_name_ne": "गोपालमान श्रेष्ठ",
        "position_type": "deputy_pm",
        "ministry": "Physical Infrastructure and Transport",
        "start_date": date(2017, 6, 9),
        "end_date": date(2018, 2, 15),
        "government_name": "Fourth Deuba Cabinet",
        "prime_minister": "Sher Bahadur Deuba",
        "party_at_appointment": "CPN (Maoist Centre)",
        "notes": "Deputy PM from Maoist Centre.",
        "source": "news_archive",
    },

    # =========================================================================
    # SECOND OLI CABINET (Feb 15, 2018 - Jul 13, 2021) - 2074-2078 BS
    # =========================================================================

    # Prime Minister
    {
        "person_name_en": "KP Sharma Oli",
        "person_name_ne": "केपी शर्मा ओली",
        "position_type": "prime_minister",
        "ministry": None,
        "start_date": date(2018, 2, 15),
        "end_date": date(2021, 7, 13),
        "government_name": "Second Oli Cabinet",
        "prime_minister": None,
        "party_at_appointment": "CPN (UML)",
        "notes": "Second term. Won 2017 election with 2/3 majority. NCP formed by merger with Maoists.",
        "source": "opmcm",
    },

    # Deputy Prime Ministers / Senior Ministers
    {
        "person_name_en": "Ishwor Pokhrel",
        "person_name_ne": "ईश्वर पोखरेल",
        "position_type": "deputy_pm",
        "ministry": "Defence",
        "start_date": date(2018, 2, 26),
        "end_date": date(2021, 7, 13),
        "government_name": "Second Oli Cabinet",
        "prime_minister": "KP Sharma Oli",
        "party_at_appointment": "CPN (UML)",
        "notes": "Deputy PM and Defence Minister. Second in rank after PM.",
        "source": "opmcm",
    },
    {
        "person_name_en": "Upendra Yadav",
        "person_name_ne": "उपेन्द्र यादव",
        "position_type": "deputy_pm",
        "ministry": "Health and Population",
        "start_date": date(2018, 2, 28),
        "end_date": date(2020, 2, 20),
        "government_name": "Second Oli Cabinet",
        "prime_minister": "KP Sharma Oli",
        "party_at_appointment": "Federal Socialist Forum Nepal",
        "notes": "Deputy PM representing Madheshi parties. Left coalition in 2020.",
        "source": "opmcm",
    },

    # Finance Minister
    {
        "person_name_en": "Yubaraj Khatiwada",
        "person_name_ne": "युवराज खतिवडा",
        "position_type": "minister",
        "ministry": "Finance",
        "start_date": date(2018, 2, 26),
        "end_date": date(2020, 10, 14),
        "government_name": "Second Oli Cabinet",
        "prime_minister": "KP Sharma Oli",
        "party_at_appointment": "Independent (Technocrat)",
        "notes": "Former NRB Governor. Non-partisan finance minister.",
        "source": "news_archive",
    },
    {
        "person_name_en": "Bishnu Prasad Paudel",
        "person_name_ne": "विष्णु प्रसाद पौडेल",
        "position_type": "minister",
        "ministry": "Finance",
        "start_date": date(2020, 10, 14),
        "end_date": date(2021, 7, 13),
        "government_name": "Second Oli Cabinet",
        "prime_minister": "KP Sharma Oli",
        "party_at_appointment": "CPN (UML)",
        "notes": "Finance Minister during COVID-19 pandemic. Second time as FM.",
        "source": "opmcm",
    },

    # Foreign Affairs
    {
        "person_name_en": "Pradeep Kumar Gyawali",
        "person_name_ne": "प्रदीपकुमार ज्ञवाली",
        "position_type": "minister",
        "ministry": "Foreign Affairs",
        "start_date": date(2018, 3, 17),
        "end_date": date(2021, 7, 13),
        "government_name": "Second Oli Cabinet",
        "prime_minister": "KP Sharma Oli",
        "party_at_appointment": "CPN (UML)",
        "notes": "Foreign Minister during India-Nepal border dispute. Updated Nepal map.",
        "source": "opmcm",
    },

    # Home Affairs
    {
        "person_name_en": "Ram Bahadur Thapa",
        "person_name_ne": "रामबहादुर थापा",
        "position_type": "minister",
        "ministry": "Home Affairs",
        "start_date": date(2018, 2, 26),
        "end_date": date(2021, 3, 13),
        "government_name": "Second Oli Cabinet",
        "prime_minister": "KP Sharma Oli",
        "party_at_appointment": "CPN (Maoist Centre)",
        "notes": "Home Minister from Maoist quota. Known as 'Badal'.",
        "source": "news_archive",
    },

    # Energy
    {
        "person_name_en": "Barshaman Pun",
        "person_name_ne": "वर्षमान पुन",
        "position_type": "minister",
        "ministry": "Energy, Water Resources and Irrigation",
        "start_date": date(2018, 3, 17),
        "end_date": date(2021, 3, 13),
        "government_name": "Second Oli Cabinet",
        "prime_minister": "KP Sharma Oli",
        "party_at_appointment": "CPN (Maoist Centre)",
        "notes": "Energy Minister. Known as 'Ananta'.",
        "source": "news_archive",
    },

    # Other key ministers
    {
        "person_name_en": "Gokarna Raj Bista",
        "person_name_ne": "गोकर्ण राज बिष्ट",
        "position_type": "minister",
        "ministry": "Labour, Employment and Social Security",
        "start_date": date(2018, 3, 17),
        "end_date": date(2021, 7, 13),
        "government_name": "Second Oli Cabinet",
        "prime_minister": "KP Sharma Oli",
        "party_at_appointment": "CPN (UML)",
        "notes": "Labour Minister.",
        "source": "news_archive",
    },
    {
        "person_name_en": "Rabindra Adhikari",
        "person_name_ne": "रविन्द्र अधिकारी",
        "position_type": "minister",
        "ministry": "Culture, Tourism and Civil Aviation",
        "start_date": date(2018, 3, 17),
        "end_date": date(2019, 2, 27),
        "government_name": "Second Oli Cabinet",
        "prime_minister": "KP Sharma Oli",
        "party_at_appointment": "CPN (UML)",
        "notes": "Tourism Minister. Died in helicopter crash in Feb 2019.",
        "source": "news_archive",
    },
    {
        "person_name_en": "Giriraj Mani Pokharel",
        "person_name_ne": "गिरिराजमणि पोखरेल",
        "position_type": "minister",
        "ministry": "Education, Science and Technology",
        "start_date": date(2018, 3, 17),
        "end_date": date(2021, 7, 13),
        "government_name": "Second Oli Cabinet",
        "prime_minister": "KP Sharma Oli",
        "party_at_appointment": "CPN (UML)",
        "notes": "Education Minister.",
        "source": "news_archive",
    },
    {
        "person_name_en": "Matrika Prasad Yadav",
        "person_name_ne": "मात्रिका प्रसाद यादव",
        "position_type": "minister",
        "ministry": "Industry, Commerce and Supplies",
        "start_date": date(2018, 2, 26),
        "end_date": date(2021, 3, 13),
        "government_name": "Second Oli Cabinet",
        "prime_minister": "KP Sharma Oli",
        "party_at_appointment": "CPN (Maoist Centre)",
        "notes": "Industry Minister from Maoist quota.",
        "source": "news_archive",
    },
    {
        "person_name_en": "Raghubir Mahaseth",
        "person_name_ne": "रघुवीर महासेठ",
        "position_type": "minister",
        "ministry": "Physical Infrastructure and Transport",
        "start_date": date(2018, 3, 17),
        "end_date": date(2021, 7, 13),
        "government_name": "Second Oli Cabinet",
        "prime_minister": "KP Sharma Oli",
        "party_at_appointment": "CPN (UML)",
        "notes": "Infrastructure Minister. From Madhesh.",
        "source": "news_archive",
    },
    {
        "person_name_en": "Shakti Bahadur Basnet",
        "person_name_ne": "शक्ति बहादुर बस्नेत",
        "position_type": "minister",
        "ministry": "Urban Development",
        "start_date": date(2018, 3, 17),
        "end_date": date(2021, 7, 13),
        "government_name": "Second Oli Cabinet",
        "prime_minister": "KP Sharma Oli",
        "party_at_appointment": "CPN (UML)",
        "notes": "Urban Development Minister.",
        "source": "news_archive",
    },
    {
        "person_name_en": "Lal Babu Pandit",
        "person_name_ne": "लालबाबु पण्डित",
        "position_type": "minister",
        "ministry": "Forest and Environment",
        "start_date": date(2018, 2, 15),
        "end_date": date(2021, 7, 13),
        "government_name": "Second Oli Cabinet",
        "prime_minister": "KP Sharma Oli",
        "party_at_appointment": "CPN (UML)",
        "notes": "One of the first two ministers sworn in with PM Oli.",
        "source": "news_archive",
    },
    {
        "person_name_en": "Tham Maya Thapa",
        "person_name_ne": "थममाया थापा",
        "position_type": "minister",
        "ministry": "Women, Children and Senior Citizens",
        "start_date": date(2018, 2, 15),
        "end_date": date(2021, 7, 13),
        "government_name": "Second Oli Cabinet",
        "prime_minister": "KP Sharma Oli",
        "party_at_appointment": "CPN (Maoist Centre)",
        "notes": "One of the first two ministers sworn in with PM Oli.",
        "source": "news_archive",
    },
    {
        "person_name_en": "Gokul Prasad Baskota",
        "person_name_ne": "गोकुल प्रसाद बास्कोटा",
        "position_type": "minister",
        "ministry": "Communications and Information Technology",
        "start_date": date(2018, 3, 17),
        "end_date": date(2020, 2, 20),
        "government_name": "Second Oli Cabinet",
        "prime_minister": "KP Sharma Oli",
        "party_at_appointment": "CPN (UML)",
        "notes": "Communications Minister. Also served as PM's spokesperson. Resigned after audio leak.",
        "source": "news_archive",
    },

    # State Ministers
    {
        "person_name_en": "Top Bahadur Rayamajhi",
        "person_name_ne": "टोपबहादुर रायमाझी",
        "position_type": "state_minister",
        "ministry": "Home Affairs",
        "start_date": date(2018, 3, 17),
        "end_date": date(2021, 7, 13),
        "government_name": "Second Oli Cabinet",
        "prime_minister": "KP Sharma Oli",
        "party_at_appointment": "CPN (UML)",
        "notes": "State Minister of Home Affairs.",
        "source": "news_archive",
    },

    # =========================================================================
    # FIFTH DEUBA CABINET (Jul 13, 2021 - Dec 25, 2022) - 2078-2079 BS
    # =========================================================================

    # Prime Minister
    {
        "person_name_en": "Sher Bahadur Deuba",
        "person_name_ne": "शेरबहादुर देउवा",
        "position_type": "prime_minister",
        "ministry": None,
        "start_date": date(2021, 7, 13),
        "end_date": date(2022, 12, 25),
        "government_name": "Fifth Deuba Cabinet",
        "prime_minister": None,
        "party_at_appointment": "Nepali Congress",
        "notes": "Fifth term as PM. Appointed by Supreme Court order.",
        "source": "opmcm",
    },

    # Key Ministers
    {
        "person_name_en": "Bal Krishna Khand",
        "person_name_ne": "बालकृष्ण खाँड",
        "position_type": "minister",
        "ministry": "Home Affairs",
        "start_date": date(2021, 7, 13),
        "end_date": date(2022, 12, 25),
        "government_name": "Fifth Deuba Cabinet",
        "prime_minister": "Sher Bahadur Deuba",
        "party_at_appointment": "Nepali Congress",
        "notes": "Home Minister throughout Deuba's fifth term.",
        "source": "news_archive",
    },
    {
        "person_name_en": "Janardan Sharma",
        "person_name_ne": "जनार्दन शर्मा",
        "position_type": "minister",
        "ministry": "Finance",
        "start_date": date(2021, 7, 13),
        "end_date": date(2022, 9, 11),
        "government_name": "Fifth Deuba Cabinet",
        "prime_minister": "Sher Bahadur Deuba",
        "party_at_appointment": "CPN (Maoist Centre)",
        "notes": "Finance Minister. Known as 'Prabhakar'. Resigned over budget controversy.",
        "source": "news_archive",
    },
    {
        "person_name_en": "Pampha Bhusal",
        "person_name_ne": "पम्फा भुसाल",
        "position_type": "minister",
        "ministry": "Energy, Water Resources and Irrigation",
        "start_date": date(2021, 7, 13),
        "end_date": date(2022, 12, 25),
        "government_name": "Fifth Deuba Cabinet",
        "prime_minister": "Sher Bahadur Deuba",
        "party_at_appointment": "CPN (Maoist Centre)",
        "notes": "Energy Minister.",
        "source": "news_archive",
    },
    {
        "person_name_en": "Gyanendra Bahadur Karki",
        "person_name_ne": "ज्ञानेन्द्र बहादुर कार्की",
        "position_type": "minister",
        "ministry": "Law, Justice and Parliamentary Affairs",
        "start_date": date(2021, 7, 13),
        "end_date": date(2021, 10, 8),
        "government_name": "Fifth Deuba Cabinet",
        "prime_minister": "Sher Bahadur Deuba",
        "party_at_appointment": "Nepali Congress",
        "notes": "Law Minister. Later shifted to Communications.",
        "source": "news_archive",
    },
    {
        "person_name_en": "Birodh Khatiwada",
        "person_name_ne": "विरोध खतिवडा",
        "position_type": "minister",
        "ministry": "Health and Population",
        "start_date": date(2021, 10, 8),
        "end_date": date(2022, 12, 25),
        "government_name": "Fifth Deuba Cabinet",
        "prime_minister": "Sher Bahadur Deuba",
        "party_at_appointment": "CPN (Unified Socialist)",
        "notes": "Health Minister during COVID-19 recovery phase.",
        "source": "news_archive",
    },
    {
        "person_name_en": "Ram Kumari Jhakri",
        "person_name_ne": "रामकुमारी झाँक्री",
        "position_type": "minister",
        "ministry": "Urban Development",
        "start_date": date(2021, 10, 8),
        "end_date": date(2022, 12, 25),
        "government_name": "Fifth Deuba Cabinet",
        "prime_minister": "Sher Bahadur Deuba",
        "party_at_appointment": "CPN (Unified Socialist)",
        "notes": "Urban Development Minister.",
        "source": "news_archive",
    },
    {
        "person_name_en": "Prem Bahadur Ale",
        "person_name_ne": "प्रेम बहादुर आले",
        "position_type": "minister",
        "ministry": "Culture, Tourism and Civil Aviation",
        "start_date": date(2021, 10, 8),
        "end_date": date(2022, 12, 25),
        "government_name": "Fifth Deuba Cabinet",
        "prime_minister": "Sher Bahadur Deuba",
        "party_at_appointment": "CPN (Unified Socialist)",
        "notes": "Tourism Minister.",
        "source": "news_archive",
    },
    {
        "person_name_en": "Devendra Paudel",
        "person_name_ne": "देवेन्द्र पौडेल",
        "position_type": "minister",
        "ministry": "Education, Science and Technology",
        "start_date": date(2021, 10, 8),
        "end_date": date(2022, 12, 25),
        "government_name": "Fifth Deuba Cabinet",
        "prime_minister": "Sher Bahadur Deuba",
        "party_at_appointment": "CPN (Maoist Centre)",
        "notes": "Education Minister.",
        "source": "news_archive",
    },
    {
        "person_name_en": "Maheshwor Gahatraj",
        "person_name_ne": "महेश्वर गहतराज",
        "position_type": "minister",
        "ministry": "Youth and Sports",
        "start_date": date(2021, 10, 8),
        "end_date": date(2022, 12, 25),
        "government_name": "Fifth Deuba Cabinet",
        "prime_minister": "Sher Bahadur Deuba",
        "party_at_appointment": "CPN (Maoist Centre)",
        "notes": "Youth and Sports Minister.",
        "source": "news_archive",
    },

    # =========================================================================
    # THIRD DAHAL CABINET (Dec 26, 2022 - Jul 12, 2024) - 2079-2081 BS
    # =========================================================================

    # Prime Minister
    {
        "person_name_en": "Pushpa Kamal Dahal",
        "person_name_ne": "पुष्पकमल दाहाल",
        "position_type": "prime_minister",
        "ministry": None,
        "start_date": date(2022, 12, 26),
        "end_date": date(2024, 7, 12),
        "government_name": "Third Dahal Cabinet",
        "prime_minister": None,
        "party_at_appointment": "CPN (Maoist Centre)",
        "notes": "Third term as PM. Multiple coalition changes during tenure.",
        "source": "opmcm",
    },

    # Deputy Prime Ministers (Initial - RSP/UML coalition)
    {
        "person_name_en": "Rabi Lamichhane",
        "person_name_ne": "रवि लामिछाने",
        "position_type": "deputy_pm",
        "ministry": "Home Affairs",
        "start_date": date(2022, 12, 26),
        "end_date": date(2024, 3, 4),
        "government_name": "Third Dahal Cabinet",
        "prime_minister": "Pushpa Kamal Dahal",
        "party_at_appointment": "Rastriya Swatantra Party",
        "notes": "First time Deputy PM and Home Minister. RSP leader. Oversaw police reforms.",
        "source": "opmcm",
    },
    {
        "person_name_en": "Bishnu Prasad Paudel",
        "person_name_ne": "विष्णु प्रसाद पौडेल",
        "position_type": "deputy_pm",
        "ministry": "Finance",
        "start_date": date(2022, 12, 26),
        "end_date": date(2023, 3, 5),
        "government_name": "Third Dahal Cabinet",
        "prime_minister": "Pushpa Kamal Dahal",
        "party_at_appointment": "CPN (UML)",
        "notes": "Deputy PM and Finance Minister (first phase with UML).",
        "source": "opmcm",
    },
    {
        "person_name_en": "Narayan Kaji Shrestha",
        "person_name_ne": "नारायणकाजी श्रेष्ठ",
        "position_type": "deputy_pm",
        "ministry": "Physical Infrastructure and Transport",
        "start_date": date(2022, 12, 26),
        "end_date": date(2024, 3, 4),
        "government_name": "Third Dahal Cabinet",
        "prime_minister": "Pushpa Kamal Dahal",
        "party_at_appointment": "CPN (Maoist Centre)",
        "notes": "Deputy PM from Maoist Centre. Known as 'Prakash'.",
        "source": "opmcm",
    },

    # Ministers (Initial coalition)
    {
        "person_name_en": "Damodar Bhandari",
        "person_name_ne": "दामोदर भण्डारी",
        "position_type": "minister",
        "ministry": "Industry, Commerce and Supplies",
        "start_date": date(2022, 12, 26),
        "end_date": date(2024, 7, 12),
        "government_name": "Third Dahal Cabinet",
        "prime_minister": "Pushpa Kamal Dahal",
        "party_at_appointment": "CPN (UML)",
        "notes": "Industry Minister.",
        "source": "news_archive",
    },
    {
        "person_name_en": "Rajendra Kumar Rai",
        "person_name_ne": "राजेन्द्र कुमार राई",
        "position_type": "minister",
        "ministry": "Water Supply",
        "start_date": date(2022, 12, 26),
        "end_date": date(2024, 7, 12),
        "government_name": "Third Dahal Cabinet",
        "prime_minister": "Pushpa Kamal Dahal",
        "party_at_appointment": "Rastriya Swatantra Party",
        "notes": "Water Supply Minister from RSP.",
        "source": "news_archive",
    },
    {
        "person_name_en": "Abdul Khan",
        "person_name_ne": "अब्दुल खान",
        "position_type": "minister",
        "ministry": "Forest and Environment",
        "start_date": date(2022, 12, 26),
        "end_date": date(2023, 3, 5),
        "government_name": "Third Dahal Cabinet",
        "prime_minister": "Pushpa Kamal Dahal",
        "party_at_appointment": "Janamat Party",
        "notes": "Forest Minister from Janamat Party.",
        "source": "news_archive",
    },
    {
        "person_name_en": "Jwala Kumari Shah",
        "person_name_ne": "ज्वालाकुमारी शाह",
        "position_type": "minister",
        "ministry": "Agriculture and Livestock Development",
        "start_date": date(2022, 12, 26),
        "end_date": date(2024, 7, 12),
        "government_name": "Third Dahal Cabinet",
        "prime_minister": "Pushpa Kamal Dahal",
        "party_at_appointment": "Rastriya Prajatantra Party",
        "notes": "Agriculture Minister from RPP.",
        "source": "news_archive",
    },

    # After coalition change (NC joins)
    {
        "person_name_en": "Purna Bahadur Khadka",
        "person_name_ne": "पूर्णबहादुर खड्का",
        "position_type": "deputy_pm",
        "ministry": "Defence",
        "start_date": date(2023, 3, 5),
        "end_date": date(2024, 3, 4),
        "government_name": "Third Dahal Cabinet",
        "prime_minister": "Pushpa Kamal Dahal",
        "party_at_appointment": "Nepali Congress",
        "notes": "Deputy PM and Defence Minister when NC joined coalition.",
        "source": "news_archive",
    },
    {
        "person_name_en": "Prakash Sharan Mahat",
        "person_name_ne": "प्रकाशशरण महत",
        "position_type": "minister",
        "ministry": "Foreign Affairs",
        "start_date": date(2023, 3, 5),
        "end_date": date(2024, 3, 4),
        "government_name": "Third Dahal Cabinet",
        "prime_minister": "Pushpa Kamal Dahal",
        "party_at_appointment": "Nepali Congress",
        "notes": "Foreign Minister from NC. Experienced diplomat.",
        "source": "news_archive",
    },
    {
        "person_name_en": "Bal Krishna Khand",
        "person_name_ne": "बालकृष्ण खाँड",
        "position_type": "minister",
        "ministry": "Home Affairs",
        "start_date": date(2023, 3, 5),
        "end_date": date(2024, 3, 4),
        "government_name": "Third Dahal Cabinet",
        "prime_minister": "Pushpa Kamal Dahal",
        "party_at_appointment": "Nepali Congress",
        "notes": "Home Minister when NC joined (replacing Rabi Lamichhane temporarily).",
        "source": "news_archive",
    },

    # After UML rejoins (March 2024)
    {
        "person_name_en": "Bishnu Prasad Paudel",
        "person_name_ne": "विष्णु प्रसाद पौडेल",
        "position_type": "deputy_pm",
        "ministry": "Finance",
        "start_date": date(2024, 3, 4),
        "end_date": date(2024, 7, 12),
        "government_name": "Third Dahal Cabinet",
        "prime_minister": "Pushpa Kamal Dahal",
        "party_at_appointment": "CPN (UML)",
        "notes": "Deputy PM and Finance Minister after UML rejoined coalition.",
        "source": "opmcm",
    },
    {
        "person_name_en": "Raghubir Mahaseth",
        "person_name_ne": "रघुवीर महासेठ",
        "position_type": "deputy_pm",
        "ministry": "Physical Infrastructure and Transport",
        "start_date": date(2024, 3, 6),
        "end_date": date(2024, 7, 12),
        "government_name": "Third Dahal Cabinet",
        "prime_minister": "Pushpa Kamal Dahal",
        "party_at_appointment": "CPN (UML)",
        "notes": "Deputy PM after UML rejoined.",
        "source": "news_archive",
    },
    {
        "person_name_en": "Narayan Kaji Shrestha",
        "person_name_ne": "नारायणकाजी श्रेष्ठ",
        "position_type": "deputy_pm",
        "ministry": "Foreign Affairs",
        "start_date": date(2024, 3, 6),
        "end_date": date(2024, 7, 12),
        "government_name": "Third Dahal Cabinet",
        "prime_minister": "Pushpa Kamal Dahal",
        "party_at_appointment": "CPN (Maoist Centre)",
        "notes": "Shifted to Foreign Affairs when UML rejoined.",
        "source": "news_archive",
    },
    {
        "person_name_en": "Barshaman Pun",
        "person_name_ne": "वर्षमान पुन",
        "position_type": "minister",
        "ministry": "Finance",
        "start_date": date(2024, 3, 6),
        "end_date": date(2024, 7, 12),
        "government_name": "Third Dahal Cabinet",
        "prime_minister": "Pushpa Kamal Dahal",
        "party_at_appointment": "CPN (Maoist Centre)",
        "notes": "Finance Minister after cabinet reshuffle.",
        "source": "news_archive",
    },
    {
        "person_name_en": "Shakti Bahadur Basnet",
        "person_name_ne": "शक्ति बहादुर बस्नेत",
        "position_type": "minister",
        "ministry": "Energy, Water Resources and Irrigation",
        "start_date": date(2024, 3, 6),
        "end_date": date(2024, 7, 12),
        "government_name": "Third Dahal Cabinet",
        "prime_minister": "Pushpa Kamal Dahal",
        "party_at_appointment": "CPN (Maoist Centre)",
        "notes": "Energy Minister after cabinet reshuffle.",
        "source": "news_archive",
    },
    {
        "person_name_en": "Rekha Sharma",
        "person_name_ne": "रेखा शर्मा",
        "position_type": "minister",
        "ministry": "Communications and Information Technology",
        "start_date": date(2024, 3, 6),
        "end_date": date(2024, 7, 12),
        "government_name": "Third Dahal Cabinet",
        "prime_minister": "Pushpa Kamal Dahal",
        "party_at_appointment": "CPN (Maoist Centre)",
        "notes": "Communications Minister.",
        "source": "news_archive",
    },
    {
        "person_name_en": "Bhagwati Chaudhary",
        "person_name_ne": "भगवती चौधरी",
        "position_type": "minister",
        "ministry": "Women, Children, and Senior Citizens",
        "start_date": date(2024, 3, 6),
        "end_date": date(2024, 7, 12),
        "government_name": "Third Dahal Cabinet",
        "prime_minister": "Pushpa Kamal Dahal",
        "party_at_appointment": "CPN (UML)",
        "notes": "Women's Affairs Minister from UML.",
        "source": "news_archive",
    },
    {
        "person_name_en": "Bhanu Bhakta Joshi",
        "person_name_ne": "भानुभक्त जोशी",
        "position_type": "minister",
        "ministry": "Federal Affairs and General Administration",
        "start_date": date(2024, 3, 6),
        "end_date": date(2024, 7, 12),
        "government_name": "Third Dahal Cabinet",
        "prime_minister": "Pushpa Kamal Dahal",
        "party_at_appointment": "CPN (Unified Socialist)",
        "notes": "From Unified Socialist party.",
        "source": "news_archive",
    },
    {
        "person_name_en": "Dhan Bahadur Budha",
        "person_name_ne": "धनबहादुर बुढा",
        "position_type": "minister",
        "ministry": "Urban Development",
        "start_date": date(2024, 3, 6),
        "end_date": date(2024, 7, 12),
        "government_name": "Third Dahal Cabinet",
        "prime_minister": "Pushpa Kamal Dahal",
        "party_at_appointment": "CPN (Unified Socialist)",
        "notes": "Urban Development Minister.",
        "source": "news_archive",
    },
    {
        "person_name_en": "Dol Prasad Aryal",
        "person_name_ne": "डोल प्रसाद अर्याल",
        "position_type": "minister",
        "ministry": "Law, Justice and Parliamentary Affairs",
        "start_date": date(2024, 3, 6),
        "end_date": date(2024, 7, 12),
        "government_name": "Third Dahal Cabinet",
        "prime_minister": "Pushpa Kamal Dahal",
        "party_at_appointment": "Rastriya Swatantra Party",
        "notes": "Law Minister from RSP.",
        "source": "news_archive",
    },
    {
        "person_name_en": "Padam Giri",
        "person_name_ne": "पदम गिरी",
        "position_type": "minister",
        "ministry": "Labour, Employment and Social Security",
        "start_date": date(2024, 3, 6),
        "end_date": date(2024, 7, 12),
        "government_name": "Third Dahal Cabinet",
        "prime_minister": "Pushpa Kamal Dahal",
        "party_at_appointment": "CPN (UML)",
        "notes": "Labour Minister from UML.",
        "source": "news_archive",
    },
    {
        "person_name_en": "Hit Bahadur Tamang",
        "person_name_ne": "हित बहादुर तामाङ",
        "position_type": "minister",
        "ministry": "Youth and Sports",
        "start_date": date(2024, 3, 6),
        "end_date": date(2024, 7, 12),
        "government_name": "Third Dahal Cabinet",
        "prime_minister": "Pushpa Kamal Dahal",
        "party_at_appointment": "CPN (Maoist Centre)",
        "notes": "Youth and Sports Minister.",
        "source": "news_archive",
    },

    # =========================================================================
    # FOURTH OLI CABINET (Jul 15, 2024 - Sep 2025) - 2081-2082 BS
    # =========================================================================

    # Prime Minister
    {
        "person_name_en": "KP Sharma Oli",
        "person_name_ne": "केपी शर्मा ओली",
        "position_type": "prime_minister",
        "ministry": None,
        "start_date": date(2024, 7, 15),
        "end_date": date(2025, 9, 12),
        "government_name": "Fourth Oli Cabinet",
        "prime_minister": None,
        "party_at_appointment": "CPN (UML)",
        "notes": "Fourth term as PM. UML-NC coalition after Dahal lost confidence vote.",
        "source": "opmcm",
    },

    # Deputy Prime Ministers
    {
        "person_name_en": "Prakash Man Singh",
        "person_name_ne": "प्रकाशमान सिंह",
        "position_type": "deputy_pm",
        "ministry": "Health and Population",
        "start_date": date(2024, 7, 15),
        "end_date": date(2025, 9, 12),
        "government_name": "Fourth Oli Cabinet",
        "prime_minister": "KP Sharma Oli",
        "party_at_appointment": "Nepali Congress",
        "notes": "Deputy PM from NC in coalition government.",
        "source": "news_archive",
    },
    {
        "person_name_en": "Bishnu Prasad Paudel",
        "person_name_ne": "विष्णु प्रसाद पौडेल",
        "position_type": "deputy_pm",
        "ministry": "Finance",
        "start_date": date(2024, 7, 15),
        "end_date": date(2025, 9, 12),
        "government_name": "Fourth Oli Cabinet",
        "prime_minister": "KP Sharma Oli",
        "party_at_appointment": "CPN (UML)",
        "notes": "Deputy PM and Finance Minister from UML.",
        "source": "news_archive",
    },

    # Key Ministers
    {
        "person_name_en": "Pradeep Kumar Gyawali",
        "person_name_ne": "प्रदीपकुमार ज्ञवाली",
        "position_type": "minister",
        "ministry": "Foreign Affairs",
        "start_date": date(2024, 7, 15),
        "end_date": date(2025, 9, 12),
        "government_name": "Fourth Oli Cabinet",
        "prime_minister": "KP Sharma Oli",
        "party_at_appointment": "CPN (UML)",
        "notes": "Foreign Minister, returning to role from 2nd Oli cabinet.",
        "source": "news_archive",
    },
    {
        "person_name_en": "Ramesh Lekhak",
        "person_name_ne": "रमेश लेखक",
        "position_type": "minister",
        "ministry": "Home Affairs",
        "start_date": date(2024, 7, 15),
        "end_date": date(2025, 9, 12),
        "government_name": "Fourth Oli Cabinet",
        "prime_minister": "KP Sharma Oli",
        "party_at_appointment": "Nepali Congress",
        "notes": "Home Minister from NC.",
        "source": "news_archive",
    },
    {
        "person_name_en": "Deepak Khadka",
        "person_name_ne": "दीपक खड्का",
        "position_type": "minister",
        "ministry": "Energy, Water Resources and Irrigation",
        "start_date": date(2024, 7, 15),
        "end_date": date(2025, 9, 12),
        "government_name": "Fourth Oli Cabinet",
        "prime_minister": "KP Sharma Oli",
        "party_at_appointment": "Nepali Congress",
        "notes": "Energy Minister from NC.",
        "source": "news_archive",
    },
    {
        "person_name_en": "Ajay Chaurasiya",
        "person_name_ne": "अजय चौरसिया",
        "position_type": "minister",
        "ministry": "Law, Justice and Parliamentary Affairs",
        "start_date": date(2024, 7, 15),
        "end_date": date(2025, 9, 12),
        "government_name": "Fourth Oli Cabinet",
        "prime_minister": "KP Sharma Oli",
        "party_at_appointment": "Nepali Congress",
        "notes": "Law Minister from NC.",
        "source": "news_archive",
    },
    {
        "person_name_en": "Aain Bahadur Shahi",
        "person_name_ne": "ऐन बहादुर शाही",
        "position_type": "minister",
        "ministry": "Forest and Environment",
        "start_date": date(2024, 7, 15),
        "end_date": date(2025, 9, 12),
        "government_name": "Fourth Oli Cabinet",
        "prime_minister": "KP Sharma Oli",
        "party_at_appointment": "Nepali Congress",
        "notes": "Forest Minister from NC.",
        "source": "news_archive",
    },
    {
        "person_name_en": "Teju Lal Chaudhary",
        "person_name_ne": "तेजूलाल चौधरी",
        "position_type": "minister",
        "ministry": "Youth and Sports",
        "start_date": date(2024, 7, 15),
        "end_date": date(2025, 9, 12),
        "government_name": "Fourth Oli Cabinet",
        "prime_minister": "KP Sharma Oli",
        "party_at_appointment": "Nepali Congress",
        "notes": "Youth and Sports Minister from NC.",
        "source": "news_archive",
    },
    {
        "person_name_en": "Giriraj Mani Pokharel",
        "person_name_ne": "गिरिराजमणि पोखरेल",
        "position_type": "minister",
        "ministry": "Education, Science and Technology",
        "start_date": date(2024, 7, 15),
        "end_date": date(2025, 9, 12),
        "government_name": "Fourth Oli Cabinet",
        "prime_minister": "KP Sharma Oli",
        "party_at_appointment": "CPN (UML)",
        "notes": "Education Minister, returning from 2nd Oli cabinet.",
        "source": "news_archive",
    },
    {
        "person_name_en": "Shakti Bahadur Basnet",
        "person_name_ne": "शक्ति बहादुर बस्नेत",
        "position_type": "minister",
        "ministry": "Defence",
        "start_date": date(2024, 7, 15),
        "end_date": date(2025, 9, 12),
        "government_name": "Fourth Oli Cabinet",
        "prime_minister": "KP Sharma Oli",
        "party_at_appointment": "CPN (UML)",
        "notes": "Defence Minister from UML.",
        "source": "news_archive",
    },
    {
        "person_name_en": "Damodar Bhandari",
        "person_name_ne": "दामोदर भण्डारी",
        "position_type": "minister",
        "ministry": "Physical Infrastructure and Transport",
        "start_date": date(2024, 7, 15),
        "end_date": date(2025, 9, 12),
        "government_name": "Fourth Oli Cabinet",
        "prime_minister": "KP Sharma Oli",
        "party_at_appointment": "CPN (UML)",
        "notes": "Infrastructure Minister from UML.",
        "source": "news_archive",
    },
]


async def seed_ministerial_positions(db: AsyncSession) -> int:
    """Seed ministerial positions data into database."""
    count = 0
    skipped = 0

    for data in MINISTERIAL_DATA:
        # Check if position already exists (avoid duplicates)
        stmt = select(MinisterialPosition).where(
            MinisterialPosition.person_name_en == data["person_name_en"],
            MinisterialPosition.position_type == data["position_type"],
            MinisterialPosition.start_date == data["start_date"],
        )
        existing = await db.execute(stmt)
        if existing.scalar_one_or_none():
            skipped += 1
            continue

        position = MinisterialPosition(
            id=uuid4(),
            person_name_en=data["person_name_en"],
            person_name_ne=data.get("person_name_ne"),
            position_type=data["position_type"],
            ministry=data.get("ministry"),
            ministry_ne=data.get("ministry_ne"),
            start_date=data["start_date"],
            end_date=data.get("end_date"),
            is_current=data.get("is_current", False),
            government_name=data.get("government_name"),
            prime_minister=data.get("prime_minister"),
            party_at_appointment=data.get("party_at_appointment"),
            notes=data.get("notes"),
            source=data.get("source", "manual"),
        )

        db.add(position)
        count += 1
        logger.info(f"Added: {data['person_name_en']} - {data.get('ministry', data['position_type'])} ({data['start_date']})")

    await db.commit()
    logger.info(f"Skipped {skipped} existing records")
    return count


async def main():
    """Main entry point."""
    logger.info("Starting comprehensive ministerial positions seed (2074-2082 BS)...")

    async with AsyncSessionLocal() as db:
        count = await seed_ministerial_positions(db)

    logger.info(f"Seeded {count} new ministerial positions")


if __name__ == "__main__":
    asyncio.run(main())
