"""SIGINT Triage model for storing interpreted signal intelligence.

Stores per-signal interpretations generated by the local SIGINT triage agent
(Haiku), including "so what" analysis for elevated economic and security signals.
"""
from datetime import datetime
from uuid import UUID, uuid4

from sqlalchemy import String, Text, Integer, DateTime, Index, func
from sqlalchemy.dialects.postgresql import UUID as PGUUID
from sqlalchemy.orm import Mapped, mapped_column

from app.models.base import Base


class SigintTriage(Base):
    """Interpreted SIGINT signal with analyst-grade "so what" assessment."""

    __tablename__ = "sigint_triage"

    id: Mapped[UUID] = mapped_column(
        PGUUID(as_uuid=True), primary_key=True, default=uuid4,
    )
    signal_title: Mapped[str] = mapped_column(String, nullable=False)
    signal_type: Mapped[str] = mapped_column(
        String(20), nullable=False,
        comment="economic or security",
    )
    severity: Mapped[str] = mapped_column(
        String(20), nullable=False,
        comment="HIGH or CRITICAL",
    )
    interpretation: Mapped[str] = mapped_column(Text, nullable=False)
    source_count: Mapped[int] = mapped_column(Integer, default=0)
    generated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False,
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(),
    )

    __table_args__ = (
        Index("ix_sigint_triage_severity", "severity"),
        Index("ix_sigint_triage_signal_type", "signal_type"),
        Index("ix_sigint_triage_created_at", "created_at"),
    )

    def __repr__(self) -> str:
        return f"<SigintTriage {self.severity} {self.signal_type}: {self.signal_title[:40]}>"
