"""SIGINT Analysis model for Sonnet-level intelligence assessments.

Stores analyst-grade intelligence briefings generated by the local Sonnet agent,
providing actionable takeaways for NEPSE traders and security analysts.
"""
from datetime import datetime
from uuid import UUID, uuid4

from sqlalchemy import String, Text, Integer, DateTime, Index, func
from sqlalchemy.dialects.postgresql import UUID as PGUUID
from sqlalchemy.orm import Mapped, mapped_column

from app.models.base import Base


class SigintAnalysis(Base):
    """Sonnet-generated intelligence assessment with actionable takeaways."""

    __tablename__ = "sigint_analysis"

    id: Mapped[UUID] = mapped_column(
        PGUUID(as_uuid=True), primary_key=True, default=uuid4,
    )
    # "market_brief" or "security_brief" or "combined"
    analysis_type: Mapped[str] = mapped_column(
        String(30), nullable=False,
        comment="market_brief, security_brief, or combined",
    )
    # Sonnet-generated headline
    headline: Mapped[str] = mapped_column(String(300), nullable=False)
    # Full analysis markdown
    analysis: Mapped[str] = mapped_column(Text, nullable=False)
    # Structured NEPSE impact assessment (JSON-like text)
    nepse_impact: Mapped[str | None] = mapped_column(Text, nullable=True)
    # Number of raw signals analyzed
    signals_analyzed: Mapped[int] = mapped_column(Integer, default=0)
    # Number of convergence clusters considered
    clusters_analyzed: Mapped[int] = mapped_column(Integer, default=0)
    # Period covered (hours)
    period_hours: Mapped[int] = mapped_column(Integer, default=48)
    generated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False,
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(),
    )

    __table_args__ = (
        Index("ix_sigint_analysis_type", "analysis_type"),
        Index("ix_sigint_analysis_created_at", "created_at"),
    )

    def __repr__(self) -> str:
        return f"<SigintAnalysis {self.analysis_type}: {self.headline[:40]}>"
